"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_TOKEN_todo"),

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'tasks',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'tasks.auth.CustomJWTAuthentication',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres', 
        'USER': 'postgres', 
        'PASSWORD': '1111',
        'HOST': '127.0.0.1', 
        'PORT': '5432',
    }
}




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),

    "AUTH_HEADER_TYPES": ("Bearer",),
    "ALGORITHM": "RS256",
    "SIGNING_KEY": """-----BEGIN RSA PRIVATE KEY-----
MIICWwIBAAKBgFLFupjgqUV1aVQVS+Ndyccv1i1MGdHLYIXDG8v739keBVI1pjo6
GoSgjumMuYeURwodjI5goMXKiBV/hYnA86CJwGOnstGRzz8Ty62dxBL83BkBVvHz
WI/iRyEEai7l+IssEHYcBwaZhuKuSD2wvNe1oA7Lb6yoMIKQSU2f247NAgMBAAEC
gYBHGOpnyIn9TJXVkJlnyja4rmFU9Uo0R3I4U1f8BfTIBR5i+Aw5dZEznMpE2AjA
6V9/09PYtC1E1+u+M5QbuC5LG2Vp5FdIBiKiEUA3cKRx/7yGqbPh3+zclfgXR26T
gMKBtT5Sd7nfd2WGyoRxHgDrlRs8Tmrr9jp2ffgRm83WgQJBAJzA4rko4O54N7yT
0FrBOefYS7pOaM2glfILXu153qqQ6ha1/rAfYSiehWC2RWJteWHM90CIPwD0DSkc
5UHtPWECQQCHLb9KQmBy55eu4t/9sSo9BJwKCI912DnPir2Hzp/0gdN2lzzjgGaC
eH3mdxTZcLDcwl0nofYkB8oHKnHtNzztAkEAiy0HIHcXHyRF+H0VJT8idqMouYYc
r1XBTGKkKh1mgfKgpQF53E5AKZx1t+SdvkKM3zTo4rcVmXcWqEYrl1lYgQJAe0G2
U1K0uPD8uMU7sgmR1vNWCDwH+07+X4RFDwjThtG97Ds4lMQmND8DpVndU+rSCWjc
IeAnHHFRwDjuinq8fQJAWRihKcWQc5+nh9xpjq79zo2bAP8B+ATu83viZQt9QX5V
tON5BAtEQd8HaWauj9tipSd2wtSXA4FM85r2c6/r5A==
-----END RSA PRIVATE KEY-----""",
    "VERIFYING_KEY": """-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgFLFupjgqUV1aVQVS+Ndyccv1i1M
GdHLYIXDG8v739keBVI1pjo6GoSgjumMuYeURwodjI5goMXKiBV/hYnA86CJwGOn
stGRzz8Ty62dxBL83BkBVvHzWI/iRyEEai7l+IssEHYcBwaZhuKuSD2wvNe1oA7L
b6yoMIKQSU2f247NAgMBAAE=
-----END PUBLIC KEY-----""",
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
AUTH_USER_MODEL = 'tasks.User'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
